{
 "title": "Canary Accounts Insights Engine",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "Consumer Received Messages",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(internal_insights_archive_received_count_total[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Engine Successfully Messages",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(internal_insights_engine_message_success_count_total[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Engine Failed Messages",
   "type": "graph",
   "gridPos": { "h": 14, "w": 7, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(internal_insights_engine_message_failure_count_total[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Successful Percentage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(internal_insights_engine_message_success_count_total[5m]))*100/(sum(increase(internal_insights_engine_message_failure_count_total[5m]))+sum(increase(internal_insights_engine_message_success_count_total[5m])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Building blocks",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Playground usage",
     "type": "text",
     "gridPos": { "h": 9, "w": 20, "x": 0, "y": 15 },
     "options": {
      "content": "# How to bulid a dashboard using this Playground\n\n"
     },
     "targets": [
      {}
     ]
    },
    {
     "title": "Graph",
     "type": "graph",
     "gridPos": { "h": 7, "w": 5, "x": 0, "y": 24 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {}
     ]
    },
    {
     "title": "SingleStat",
     "type": "stat",
     "gridPos": { "h": 7, "w": 5, "x": 5, "y": 24 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {}
     ]
    },
    {
     "title": "Table",
     "type": "table-old",
     "gridPos": { "h": 7, "w": 5, "x": 10, "y": 24 },
     "targets": [
      {}
     ]
    },
    {
     "title": "Text",
     "type": "text",
     "gridPos": { "h": 7, "w": 5, "x": 15, "y": 24 },
     "options": { "content": "# title" },
     "targets": [
      {}
     ]
    },
    {
     "title": "Heatmap",
     "type": "heatmap",
     "gridPos": { "h": 7, "w": 5, "x": 0, "y": 31 },
     "targets": [
      {}
     ]
    },
    {
     "title": "Alert list",
     "type": "alertlist",
     "gridPos": { "h": 7, "w": 5, "x": 5, "y": 31 },
     "targets": [
      {}
     ]
    },
    {
     "title": "Dashboard list",
     "type": "dashlist",
     "gridPos": { "h": 7, "w": 5, "x": 10, "y": 31 },
     "targets": [
      {}
     ]
    },
    {
     "title": "Plugin list",
     "type": "pluginlist",
     "gridPos": { "h": 7, "w": 5, "x": 15, "y": 31 },
     "targets": [
      {}
     ]
    }
   ]
  },
  {
   "title": "Row",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 },
   "collapsed": true,
   "targets": [
    {}
   ]
  },
  {
   "title": "Row",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 },
   "collapsed": true,
   "targets": [
    {}
   ]
  },
  {
   "title": "Row",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 },
   "collapsed": true,
   "targets": [
    {}
   ]
  }
 ]
}